//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areacuadrado", ReplyAction="*")]
        decimal areacuadrado(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areacuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> areacuadradoAsync(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areatriangulo", ReplyAction="*")]
        decimal areatriangulo(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areatriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> areatrianguloAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areacirculo", ReplyAction="*")]
        decimal areacirculo(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/areacirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> areacirculoAsync(decimal n1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Cliente.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Cliente.ServiceReference1.WebService1Soap>, Cliente.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal areacuadrado(decimal n1) {
            return base.Channel.areacuadrado(n1);
        }
        
        public System.Threading.Tasks.Task<decimal> areacuadradoAsync(decimal n1) {
            return base.Channel.areacuadradoAsync(n1);
        }
        
        public decimal areatriangulo(decimal n1, decimal n2) {
            return base.Channel.areatriangulo(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> areatrianguloAsync(decimal n1, decimal n2) {
            return base.Channel.areatrianguloAsync(n1, n2);
        }
        
        public decimal areacirculo(decimal n1) {
            return base.Channel.areacirculo(n1);
        }
        
        public System.Threading.Tasks.Task<decimal> areacirculoAsync(decimal n1) {
            return base.Channel.areacirculoAsync(n1);
        }
    }
}
